compliance_controller:
  simulate: false
  kp: [6500.0, 6885.0, 9850.0, 1400.0, 1400.0, 1400.0]
  #kp: [6500.0, 6500.0, 6500.0, 1000.0, 1000.0, 1000.0]
  #kp: [3250.0, 3250.0, 3250.0, 500.0, 500.0, 500.0]
  kd: [230.0, 645.0, 975.0, 10.0, 10.0, 10.0]
  #kd: [230.0, 645.0, 975.0, 100.0, 100.0, 100.0]
  joint_state_topic: "/bravo/joint_states"
  ee_state_topic: "/bravo/ee_state"
  effort_cmd_topic: "/bravo/arm_effort_controller/command"
  toggle_cc_service_topic: "/bravo/compliance_controller/enable_compliance_controller"
  cc_cmd_topic: "/bravo/compliance_controller/command"
  ee_frame: "bravo_peg_link"

  # things for the error clipping
  clip_error: true
  trans_max_error: 0.01 # m (1cm)
  rot_max_error: 0.1 # rad (~6 deg)

  # things for collision
  use_self_collision_avoidance: true
  stop_on_collision: true # will not work if use_self_collision set to false
  look_ahead_dt: 0.1

  # how much to push the robot away when collision is about to happen
  pos_repulse: 2.0
  rot_repulse: 0.0 # 1.0 = no repulsion

  # use ft_interrupt
  with_ft_sensor_interrupt: true